FROM openjdk:8u212-slim
# 设置软件源为阿里源
RUN echo 'deb http://mirrors.aliyun.com/debian/ buster main non-free contrib \
    deb-src http://mirrors.aliyun.com/debian/ buster main non-free contrib \
    deb http://mirrors.aliyun.com/debian-security buster/updates main \
    deb-src http://mirrors.aliyun.com/debian-security buster/updates main \
    deb http://mirrors.aliyun.com/debian/ buster-updates main non-free contrib \
    deb-src http://mirrors.aliyun.com/debian/ buster-updates main non-free contrib \
    deb http://mirrors.aliyun.com/debian/ buster-backports main non-free contrib \
    deb-src http://mirrors.aliyun.com/debian/ buster-backports main non-free contrib'> /etc/apt/sources.list
# 更新软件源并且安装基础软件
RUN apt-get update && apt-get install -y curl
