tomshidi:
  enabled: true
  user-map:
    tom:
      - id: 1
        name: tomshidi
    tohka:
      - id: 2
        name: tohka
  prefix: name
  num: 1
  name-1: tom
  execution-time: 10S


spring:
  profiles:
    active: dev
  application:
    name: config-test
  banner:
    image:
#      location: static/banner.png
#      location: file://C:\\Users\\admin\\Desktop\\0a3d0f53-07ad-45f2-ab32-9c94e4b0f514.png
  gson:
    disable-html-escaping: true
  mvc:
    # 静态资源访问路径前缀
    static-path-pattern: /static/**

logging:
  level:
#    root: debug
    aaa: debug
#  pattern:
#    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan}[line:%line]    %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"


management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.66:8761/eureka
    enabled: false
server:
  port: 8090